services:
  idf:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    working_dir: /workspaces/SVEA-PX4-Autopilot-MCU-Peripheral
    volumes:
      - .:/workspaces/SVEA-PX4-Autopilot-MCU-Peripheral
    stdin_open: true
    tty: true
    init: true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    command: zsh -lc "sleep infinity"
